### ISSUE TITLE
project FOREIGN KEY constraint in jobs

### ISSUE THREAD

**Issue by ErmiasG** [hopshadoop/hopsworks-chef#15]
if there is an entry in the jobs table project can not be deleted b/c of the no action constraint in
FOREIGN KEY (`project_id`) REFERENCES `project` (`id`) ON DELETE ACTION ON UPDATE NO ACTION

**Comment by jimdowling** [comment]
Has this been resolved?

**Comment by jimdowling** [comment]
@ErmiasG has this been resolved?
The FK is still there:

CREATE TABLE `jobs` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) DEFAULT NULL,
  `creation_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `project_id` INT(11) NOT NULL,
  `creator` VARCHAR(150) NOT NULL,
  `type` VARCHAR(128) NOT NULL,
  `json_config` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY name_idx (`name`),
  FOREIGN KEY (`project_id`) REFERENCES `project` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  FOREIGN KEY (`creator`) REFERENCES `users` (`email`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=ndbcluster;
