### ISSUE TITLE
Flink streaming binaries

### ISSUE THREAD

**Issue by tkakantousis** [hopshadoop/hopsworks-chef#37]
When using Flink 1.0.3, the HopsWorks Kafka Utility jar and the flink filesystem connector jar need to be stored in the local flink lib directory.
The flink connector is available [here](http://central.maven.org/maven2/org/apache/flink/flink-connector-filesystem_2.10/1.0.3/flink-connector-filesystem_2.10-1.0.3.jar)

**Comment by jimdowling** [comment]
On every host? In what directory? This is actually a bug for the flink-chef cookbook...

**Comment by jimdowling** [comment]
Actually, we only install flink on the glassfish machine, so i guess it's in the local flink deployment there.... It's still a flink-chef issue.

**Comment by jimdowling** [comment]
Fixed here.
https://github.com/hopshadoop/flink-chef/issues/6
