### ISSUE TITLE
LDAP Authentication

### ISSUE THREAD

**Issue by jimdowling** [hopshadoop/hopsworks-chef#38]
Glassfish supports LDAP as an authentication module.
We should support automated installation of LDAP as the default authentication system by adding chef attributes for 'node.hopsworks.use_ldap=true' and 'node.hopsworks.ldap.server=ldap.kth.se'

Here are some links for getting started:
https://docs.oracle.com/cd/E18930_01/html/821-2435/ggkuk.html#gkbjp
http://idiotechie.com/secure-web-application-in-java-ee6-using-ldap/

**Comment by tkakantousis** [comment]
Implemented by [HOPSWORKS-113](https://hopshadoop.atlassian.net/browse/HOPSWORKS-113)
