### ISSUE TITLE
fails in vagrant with vagrant-cachier

### ISSUE THREAD

**Issue by Raboo** [hopshadoop/hopsworks-chef#4]
This chef-repo fails when running within vagrant cause of it not being able to chown files under cached locations if vagrant plugin vagrant-cachier is installed.

vagrant-cachier mounts under /tmp/vagrant-cache and /var/chef/cache symlinks to /tmp/vagrant-cache/chef.
And it cannot chown files to root that is nfs mounted in /tmp/vagrant-cache.

**Comment by Raboo** [comment]
Adding these lines to Vagrantfile worked for me.
```
  if Vagrant.has_plugin?("vagrant-cachier")
    c.cache.auto_detect = false
    c.cache.enable :apt
  end
  c.omnibus.cache_packages = false
```

**Comment by jimdowling** [comment]
Thanks, i'll add them. Be warned that this project is still under heavy development, and we have no documentation yet. Soon....
