### ISSUE TITLE
fail to modify user in vagrant

### ISSUE THREAD

**Issue by Raboo** [hopshadoop/hopsworks-chef#5]
running vagrant up fails at a step where elastic::install tries to run usermod on the vagrant user.
It tries to usermod the vagrant user, which in turn runs the entire provisioning process..

So in effect, vagrant user is logged in with running processes, and usermod fails cause vagrant user is logged in and have running processes.
catch-22.

```
==> default: ---- Begin output of ["usermod", "-c", "Elasticsearch User", "-d", "/usr/local/elasticsearch", "vagrant"] ----
==> default:
==> default:
==> default: STDOUT:
==> default:
==> default:
==> default: STDERR: usermod: user vagrant is currently used by process 1414
==> default:
==> default:
==> default: ---- End output of ["usermod", "-c", "Elasticsearch User", "-d", "/usr/local/elasticsearch", "vagrant"] ----
```

**Comment by jimdowling** [comment]
We recommend not installing as vagrant user. Try 'glassfish' user.
