### ISSUE TITLE
No recipe slave for cookbook spark

### ISSUE THREAD

**Issue by mherr** [hopshadoop/hopsworks-chef#6]
issuing <code>vagrant up</code>fails with the following error:

<code>
==> default: ERROR: could not find recipe slave for cookbook spark

==> default: FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully</code>

Any advice would be appreciated.

**Comment by jimdowling** [comment]
Sorry, this is still under heavy development. Kitchen is the primary platform we work from, so the vagrantfile is out of date. We renamed the recipe to 'worker'. I will push a fix.

**Comment by mherr** [comment]
Fixed! Thanks guys!
