### ISSUE TITLE
sudo chef-solo -c solo.rb -j hopsworks.json error

### ISSUE THREAD

**Issue by gholamiali** [hopshadoop/hopsworks-chef#7]
When I try "sudo chef-solo -c solo.rb -j hopsworks.json" I get the following error:

===================
Starting Chef Client, version 12.4.3
Compiling Cookbooks...
/tmp/cookbooks/flink/libraries/inifile.rb:11: warning: already initialized constant IniFile::VERSION
/tmp/cookbooks/kagent/libraries/inifile.rb:11: warning: previous definition of VERSION was here
/tmp/cookbooks/kagent/libraries/inifile.rb:11: warning: already initialized constant IniFile::VERSION
/tmp/cookbooks/flink/libraries/inifile.rb:11: warning: previous definition of VERSION was here
[2015-11-17T11:17:50+01:00] ERROR: Invalid cookbook/recipe name: elastic/default

================================================================================
Recipe Compile Error in /tmp/cookbooks/hopsworks/recipes/default.rb
================================================================================

ArgumentError
-------------
Invalid Recipe fo cookbook elastic

Running handlers:
[2015-11-17T11:17:50+01:00] ERROR: Running exception handlers
Running handlers complete
[2015-11-17T11:17:50+01:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 1.708903164 seconds
[2015-11-17T11:17:50+01:00] FATAL: Stacktrace dumped to /tmp/chef/chef-stacktrace.out
[2015-11-17T11:17:50+01:00] ERROR: Invalid Recipe fo cookbook elastic
[2015-11-17T11:17:50+01:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by jimdowling** [comment]
It didn't find elastic::default recipe. My guess is you missed the berks vendor step.
Try and follow instructions here:
http://www.hops.io/?q=content/development-enviornment-setup-hopsworks
If you have problems, post them here, we'll fix them.

**Comment by gholamiali** [comment]
I have: Chef: 12.4.3 and Beks: 3.3.0.

berks vendor /tmp/cookbooks
wget http://snurran.sics.se/hops/hopsworks/solo.rb
wget http://snurran.sics.se/hops/hopsworks/hopsworks.json
perl -pi -e "s/jdowling/$USER/g" hopsworks.json
perl -pi -e "s/127\.0\.0\.1/10\.0\.2\.15/g" hopsworks.json (replaced with my ip)
sudo apt-get update -y

Still I get the same error when executing this command:
sudo chef-solo -c solo.rb -j hopsworks.json

**Comment by gholamiali** [comment]
This is fixed after the update of today from the master branch
